
language: python # Set the build language to Python

python: 3.6 # Set the version of Python to use

branches: dev # Set the branch to build from

install:
  - pip install mkdocs-bootstrap

script:
  - mkdir docs
  - mv monticore-grammar docs/monticore-grammar
  - mv monticore-runtime docs/monticore-runtime
  - mv 00.org docs/00.org
  - mv *.md docs

before_deploy:
  - mkdocs build --verbose --clean --strict # Build a local version of the docs


deploy: # Deploy documentation to Github in the gh_pages branch
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: site
  on:
    branch: dev